version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node-backend-app
    restart: unless-stopped
    expose:
      - "3000"       

  frontend:
    build: ./frontend
    container_name: react-nginx-app
    ports:
      - "5001:80"     
    restart: unless-stopped
    depends_on:
      - backend
